# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def ClassifyTicket(self, ticket: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TicketClassification:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ClassifyTicket", args={
            "ticket": ticket,
        })
        return typing.cast(types.TicketClassification, result.cast_to(types, types, stream_types, False, __runtime__))
    async def DraftSupportResponse(self, ticket: str,classification: types.TicketClassification,facts: types.TicketFacts,
        baml_options: BamlCallOptions = {},
    ) -> types.DraftResponse:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="DraftSupportResponse", args={
            "ticket": ticket,"classification": classification,"facts": facts,
        })
        return typing.cast(types.DraftResponse, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractTicketFacts(self, ticket: str,classification: types.TicketClassification,
        baml_options: BamlCallOptions = {},
    ) -> types.TicketFacts:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractTicketFacts", args={
            "ticket": ticket,"classification": classification,
        })
        return typing.cast(types.TicketFacts, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyTicket(self, ticket: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.TicketClassification, types.TicketClassification]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ClassifyTicket", args={
            "ticket": ticket,
        })
        return baml_py.BamlStream[stream_types.TicketClassification, types.TicketClassification](
          result,
          lambda x: typing.cast(stream_types.TicketClassification, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TicketClassification, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def DraftSupportResponse(self, ticket: str,classification: types.TicketClassification,facts: types.TicketFacts,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DraftResponse, types.DraftResponse]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="DraftSupportResponse", args={
            "ticket": ticket,"classification": classification,"facts": facts,
        })
        return baml_py.BamlStream[stream_types.DraftResponse, types.DraftResponse](
          result,
          lambda x: typing.cast(stream_types.DraftResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DraftResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractTicketFacts(self, ticket: str,classification: types.TicketClassification,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.TicketFacts, types.TicketFacts]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractTicketFacts", args={
            "ticket": ticket,"classification": classification,
        })
        return baml_py.BamlStream[stream_types.TicketFacts, types.TicketFacts](
          result,
          lambda x: typing.cast(stream_types.TicketFacts, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TicketFacts, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ClassifyTicket(self, ticket: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyTicket", args={
            "ticket": ticket,
        }, mode="request")
        return result
    async def DraftSupportResponse(self, ticket: str,classification: types.TicketClassification,facts: types.TicketFacts,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DraftSupportResponse", args={
            "ticket": ticket,"classification": classification,"facts": facts,
        }, mode="request")
        return result
    async def ExtractTicketFacts(self, ticket: str,classification: types.TicketClassification,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractTicketFacts", args={
            "ticket": ticket,"classification": classification,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ClassifyTicket(self, ticket: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyTicket", args={
            "ticket": ticket,
        }, mode="stream")
        return result
    async def DraftSupportResponse(self, ticket: str,classification: types.TicketClassification,facts: types.TicketFacts,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DraftSupportResponse", args={
            "ticket": ticket,"classification": classification,"facts": facts,
        }, mode="stream")
        return result
    async def ExtractTicketFacts(self, ticket: str,classification: types.TicketClassification,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractTicketFacts", args={
            "ticket": ticket,"classification": classification,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))