# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyTicket(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TicketClassification:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyTicket", llm_response=llm_response, mode="request")
        return typing.cast(types.TicketClassification, result)

    def DraftSupportResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DraftResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DraftSupportResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.DraftResponse, result)

    def ExtractTicketFacts(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TicketFacts:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTicketFacts", llm_response=llm_response, mode="request")
        return typing.cast(types.TicketFacts, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyTicket(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TicketClassification:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyTicket", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TicketClassification, result)

    def DraftSupportResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DraftResponse:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DraftSupportResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DraftResponse, result)

    def ExtractTicketFacts(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TicketFacts:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTicketFacts", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TicketFacts, result)

    