# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class DraftResponse(BaseModel):
    draft_response: typing.Optional[str] = None
    tone: typing.Optional[typing.Union[str, str, str, str]] = None
    promised_actions: typing.List[str]
    safety_notes: typing.List[str]

class TicketClassification(BaseModel):
    category: typing.Optional[types.Category] = None
    urgency: typing.Optional[types.Urgency] = None
    team: typing.Optional[types.Team] = None
    needs_human_review: typing.Optional[bool] = None
    rationale: typing.Optional[str] = None

class TicketFacts(BaseModel):
    summary: typing.Optional[str] = None
    grounded_facts: typing.List[str]
    missing_information: typing.List[str]
    customer_impact: typing.Optional[str] = None
    risk_signals: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
