# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class Category(str, Enum):
    BUG = "BUG"
    OUTAGE = "OUTAGE"
    BILLING = "BILLING"
    SECURITY = "SECURITY"
    FEATURE_REQUEST = "FEATURE_REQUEST"
    DATA_LOSS = "DATA_LOSS"
    INTEGRATION_FAILURE = "INTEGRATION_FAILURE"
    PERFORMANCE = "PERFORMANCE"
    ACCOUNT_ACCESS = "ACCOUNT_ACCESS"
    COMPLIANCE_PRIVACY = "COMPLIANCE_PRIVACY"
    HOW_TO = "HOW_TO"
    UNCLEAR = "UNCLEAR"

class Team(str, Enum):
    SUPPORT = "SUPPORT"
    ENGINEERING = "ENGINEERING"
    SECURITY = "SECURITY"
    BILLING = "BILLING"
    CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS"
    COMPLIANCE = "COMPLIANCE"

class Urgency(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

# #########################################################################
# Generated classes (3)
# #########################################################################

class DraftResponse(BaseModel):
    draft_response: str
    tone: typing.Union[typing_extensions.Literal['calm'], typing_extensions.Literal['apologetic'], typing_extensions.Literal['clarifying'], typing_extensions.Literal['escalation']]
    promised_actions: typing.List[str]
    safety_notes: typing.List[str]

class TicketClassification(BaseModel):
    category: Category
    urgency: Urgency
    team: Team
    needs_human_review: bool
    rationale: str

class TicketFacts(BaseModel):
    summary: str
    grounded_facts: typing.List[str]
    missing_information: typing.List[str]
    customer_impact: str
    risk_signals: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
