# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DraftResponse": types.DraftResponse,
    "stream_types.DraftResponse": stream_types.DraftResponse,

    "types.TicketClassification": types.TicketClassification,
    "stream_types.TicketClassification": stream_types.TicketClassification,

    "types.TicketFacts": types.TicketFacts,
    "stream_types.TicketFacts": stream_types.TicketFacts,


    "types.Category": types.Category,

    "types.Team": types.Team,

    "types.Urgency": types.Urgency,

}